import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {makeDispatchHandler} from '../supabase/functions/dispatch/handler.mjs';
const D=createRequire(import.meta.url)('../dist/homebase-dispatch.js');
const offer={record_id:'trip-1',platform:'Empower',source:'screenshot',completeness:'partial',confidence:.8,fare:24,trip_time:30,trip_distance:17,pickup_time:5,pickup_distance:2,request_time:'2026-10-05T10:00:00-04:00',origin:'Washington DC',destination:'Laurel',pickup_location:[38.907,-77.036],dropoff_location:[39.099,-76.848]};
const state={mode:'GET ME HOME',location:offer.pickup_location,destination:[39.2904,-76.6122],fuelCostPerMile:.17,reservePerMile:.2,costPerMile:.37};
test('paid reposition scores destination progress and total-mile costs',()=>{const r=D.scoreTrip(offer,state);assert.ok(r.home_progress>10);assert.ok(r.paid_miles_to_destination_percent>50);assert.equal(r.net_estimate,24-19*.37);assert.equal(r.dollars_total_mile,24/19);assert.equal(r.net_online_hourly_estimate,null);assert.ok(r.factors.some(f=>f.key==='reposition'));});
test('missing pickup or cost data does not invent net profitability',()=>{const r=D.scoreTrip({...offer,pickup_time:null},{...state,fuelCostPerMile:null});assert.equal(r.trip_score,null);assert.equal(r.net_estimate,null);assert.equal(r.net_offer_hourly,null);assert.match(r.voice,/need/);});
test('Diamond strategy never issues repeated Uber decline advice',()=>{const r=D.scoreTrip({...offer,platform:'Uber',fare:5},{...state,mode:'DIAMOND MODE'});assert.equal(r.action,'acceptance_strategy');assert.doesNotMatch(r.voice,/decline/);});
test('API and screenshot duplicates collapse; unknown timestamp trips do not',()=>{const api={...offer,record_id:'api-new',source:'provider',completeness:'complete'};const r=D.mergeTrips([offer],[api]);assert.equal(r.rows.length,1);assert.equal(r.rows[0].source,'provider');assert.equal(r.rows[0].record_id,offer.record_id);const unknown=D.mergeTrips([{...offer,request_time:null}],[{...offer,record_id:'different',request_time:null}]);assert.equal(unknown.rows.length,2);});
test('booked/active earnings never become online or net earnings',()=>{const r=D.profitability([{...D.normalizeTrip(offer),status:'completed'}]);assert.equal(r.grossActiveHourly,48);assert.equal(r.grossOnlineHourly,null);assert.equal(r.netOnlineHourly,null);assert.equal(r.net,null);assert.equal(r.coverage,'partial/unknown');});
test('wait economics and threshold depend on available inputs',()=>{const r=D.opportunity({hourlyRate:32,waitMinutes:10,moveMinutes:8,moveCost:3,expectedWaitBenefit:1,nextZoneHourlyRate:36});assert.ok(Math.abs(r.wait_cost-5.333333)<.001);assert.ok(r.wait_threshold_minutes>0);assert.notEqual(r.wait_threshold_minutes,8);assert.equal(D.opportunity({hourlyRate:32}).wait_threshold_minutes,null);});
test('Empower expansion is effective-dated and explicitly user-reported',()=>{assert.equal(D.serviceArea('Empower','2026-09-30'),null);const area=D.serviceArea('Empower','2026-10-01');assert.ok(area.markets.includes('Northern Virginia'));assert.equal(area.source,'USER-REPORTED');assert.equal(area.geometry,null);});
test('freshness respects timestamps and never marks predicted feeds live',()=>{const now=Date.now();assert.equal(D.feedStatus([{name:'demand',provenance:'PREDICTED',observedAt:new Date(now).toISOString()}],now).color,'yellow');assert.equal(D.feedStatus([{name:'Uber',provenance:'LIVE',observedAt:new Date(now-7200000).toISOString()}],now).rows[0].status,'recent');assert.equal(D.feedStatus([{provenance:'LIVE',observedAt:new Date(now+1000).toISOString()}],now).color,'gray');});
test('unsupported actions are advisory and never invoke execution',async()=>{let called=false;const adapter=new D.PlatformAdapter('Uber',D.CAPABILITIES,async()=>{called=true;return{confirmed:true};});const r=await adapter.execute('accept_trip');assert.equal(r.executed,false);assert.equal(called,false);const verified={Uber:{accept_trip:{supported:true,evidence:'https://official.example'}}};const unconfirmed=await new D.PlatformAdapter('Uber',verified,async()=>({confirmed:false})).execute('accept_trip');assert.equal(unconfirmed.executed,false);});
test('stale GPS and in-progress passenger trip prevent repositioning',()=>{assert.equal(D.recommend(state,{locationAt:'2000-01-01'}).confidence,0);assert.equal(D.recommend(state,{locationAt:new Date().toISOString(),activeTrip:true}).action,'WAIT');});
test('Get Me Home uses selective platform without unsupported execution',()=>{const r=D.recommend(state,{locationAt:new Date().toISOString(),platforms:['Uber','Empower']});assert.equal(r.platform,'Empower');assert.equal(r.execution,'advisory');assert.match(r.voice,/Pause Uber manually/);});
test('personal learning requires outcomes and remains bounded',()=>{assert.equal(D.learn([]).status,'insufficient outcomes');const r=D.learn(Array.from({length:6},()=>({followed:true,net:100,minutes:30,miles:10})));assert.equal(r.weights.profit,1.2);});
test('voice commands resolve objectives and control intents',()=>{assert.equal(D.parseCommand('Home Base, get me home').mode,'GET ME HOME');assert.equal(D.parseCommand('switch to Diamond mode').mode,'DIAMOND MODE');assert.equal(D.parseCommand('Do it').type,'do it');assert.equal(D.parseCommand('Quiet for thirty minutes').minutes,30);});
test('dispatch endpoint authenticates and keeps execution advisory',async()=>{const handler=makeDispatchHandler({engine:D,authenticate:async()=>({id:'driver'}),loadState:async()=>state,loadTrips:async()=>[]});assert.equal((await handler(new Request('https://example.test',{method:'POST',body:'{}'}))).status,401);const r=await handler(new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer token'},body:JSON.stringify({operation:'score',trip:offer})}));assert.equal(r.status,200);const json=await r.json();assert.equal(json.execution,'advisory');assert.equal(json.server_evaluated,true);});
test('recurrence requires completed trips on three independent matching dates',()=>{const now=new Date('2026-10-05T10:30:00-04:00'),make=date=>({...offer,status:'completed',request_time:date});assert.equal(D.recurringTripSignal([make('2026-09-28T10:00:00-04:00')],offer.dropoff_location,now).boost,0);const trips=['2026-09-28','2026-09-21','2026-09-14'].map(d=>make(d+'T10:00:00-04:00'));assert.ok(D.recurringTripSignal(trips,offer.dropoff_location,now).boost>0);assert.equal(D.recurringTripSignal(trips.map(t=>({...t,status:'offer'})),offer.dropoff_location,now).boost,0);});
test('voice target handles additional earnings without rewriting history',()=>{const c=D.parseCommand('80 dollars more then home');assert.equal(c.type,'target');assert.equal(c.amount,80);assert.equal(c.additional,true);assert.equal(c.thenHome,true);});
test('geographic recommendations reuse predicted neighborhood zones',()=>{const r=D.recommend({...state,mode:'MAX PROFIT'},{locationAt:new Date().toISOString(),zones:[{name:'Laurel',location:offer.dropoff_location,score:.8}]});assert.equal(r.action,'REPOSITION');assert.match(r.voice,/paid miles/);assert.match(r.voice,/demand model/);});
import {makeLanguageParser} from '../supabase/functions/dispatch/language.mjs';
test('cloud language falls back without credentials and never returns an execution receipt',async()=>{const parse=makeLanguageParser({engine:D});const r=await parse('paid rides toward my place please');assert.equal(r.execution,'advisory');assert.equal(r.provider,'not_configured');const local=await parse('get me home');assert.equal(local.command.mode,'GET ME HOME');});
test('cloud language validates structured intents before local actions',async()=>{let request;const parse=makeLanguageParser({engine:D,apiKey:'test-not-a-real-key',model:'configured-model',fetchImpl:async(url,options)=>{request=JSON.parse(options.body);return new Response(JSON.stringify({output:[{content:[{type:'output_text',text:JSON.stringify({type:'mode',mode:'GET ME HOME',amount:null,additional:false,thenHome:false,remaining:false})}]}]}));}});const r=await parse('paid rides toward my place please');assert.equal(r.command.mode,'GET ME HOME');assert.equal(request.store,false);assert.equal(request.text.format.strict,true);assert.equal(r.execution,'advisory');});
test('stored vehicle profile supplies scoring costs without duplicate configuration',()=>{const r=D.scoreTrip(offer,{vehicle:{fuelCostPerMile:.17,reservePerMile:.2}});assert.ok(r.trip_score!==null);assert.equal(r.net_estimate,24-19*.37);});
test('same trip ID accepts final-fare corrections and never reverts completion',()=>{
 const completed={...offer,status:'completed'};
 const revised=D.mergeTrips([completed],[{...completed,fare:26,tip:4}]);
 assert.equal(revised.rows.length,1);assert.equal(revised.rows[0].fare,26);assert.equal(revised.rows[0].tip,4);assert.equal(revised.updated,1);
 const stale=D.mergeTrips(revised.rows,[{...offer,status:'offer'}]);assert.equal(stale.rows[0].status,'completed');assert.equal(stale.rows[0].fare,26);
});
test('losses and zero-mile waits participate in personal calibration',()=>{
 const result=D.learn(Array.from({length:5},()=>({followed:true,net:-6,minutes:30,miles:0})));
 assert.equal(result.sampleCount,5);assert.equal(result.netHourly,-12);assert.equal(result.weights.profit,.8);
});
test('reviewed trips enter the shared ledger without duplicating platform/day summaries',()=>{
 const completed={...D.normalizeTrip(offer),status:'completed'};
 const other={...completed,record_id:'trip-2',request_time:'2026-10-05T12:00:00-04:00'};
 const tripsOnly=D.earningsRecords([],[completed,other]);assert.equal(tripsOnly.length,2);assert.equal(tripsOnly[0].hoursType,'active');assert.equal(D.ledgerTotals(tripsOnly).gross,48);assert.equal(D.ledgerTotals(tripsOnly).grossOnlineHourly,null);
 const summary={id:'shift:1',platform:'Empower',date:'2026-10-05',earnings:100,payType:'gross',hoursType:'unknown',hours:5,shiftHours:5,miles:90,costs:0};
 const withSummary=D.earningsRecords([summary],[completed,other]);assert.equal(withSummary.length,1);assert.equal(D.ledgerTotals(withSummary,state).gross,100);assert.equal(D.ledgerTotals(withSummary,state).netShiftHourly,(100-90*.37)/5);assert.equal(D.ledgerTotals(withSummary,state).netOnlineHourly,null);
 const online=D.ledgerTotals([{...summary,hoursType:'online',hours:4}],state);assert.equal(online.netOnlineHourly,(100-90*.37)/4);
});
test('Diamond recovery uses selective repositioning without discarding acceptance preference',()=>{
 const recovering={...state,mode:'DIAMOND MODE',recovery:{active:true},paidRepositioning:true,diamond:true};
 const rec=D.recommend(recovering,{locationAt:new Date().toISOString(),platforms:['Uber','Empower']});assert.equal(rec.platform,'Empower');assert.ok(rec.factors.some(f=>f.includes('Previous trip')));
 assert.equal(D.scoreTrip({...offer,platform:'Uber',fare:3},{...recovering,mode:'GET ME HOME'}).action,'acceptance_strategy');
 assert.equal(D.recommend({...state,mode:'GET ME HOME'},{locationAt:new Date().toISOString(),platforms:['Uber']}).action,'RETURN HOME');
 assert.equal(D.recommend(state,{locationAt:new Date(Date.now()+10000).toISOString()}).confidence,0);
});
test('daily and weekly voice goals preserve their scope and metric',()=>{
 assert.equal(D.parseCommand('300 dollars this week').period,'week');assert.equal(D.parseCommand('80 dollars net more then home').kind,'net');assert.equal(D.parseCommand('Should I take this?').type,'offer_query');assert.equal(D.parseCommand('Stay within 20 miles of Baltimore').value,20);
});
test('shortcut handoff supports only Home Base objectives and never platform execution',()=>{
 assert.equal(D.shortcutCommand('get-me-home').mode,'GET ME HOME');assert.equal(D.shortcutCommand('pause').type,'pause');assert.equal(D.shortcutCommand('do it'),null);assert.equal(D.shortcutCommand('accept_trip'),null);assert.equal(D.localDay('2026-10-05T10:00:00Z',null),'2026-10-05');
});
